name: flutter_bluetooth_serial_example
version: 0.2.2
description: Demonstrates how to use the `flutter_bluetooth_serial` plugin.
authors: 
- Patryk Ludwikowski <patryk.ludwikowski.7@gmail.com>
homepage: https://github.com/edufolly/flutter_bluetooth_serial/tree/master/example/

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  scoped_model: ^1.0.1

  cupertino_icons: ^0.1.2
  sqflite: ^1.1.7+1
  grouped_buttons: ^1.0.4
  basic_utils: ^2.3.7
  flutter_typeahead: ^1.7.0
  image_picker: ^0.6.2+1
  video_player: ^0.10.3+3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bluetooth_serial:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/vinculacion_db.db
    - assets/images/
